### ISSUE TITLE
Gnocchi: full archive policies support

### ISSUE THREAD

**Issue by ozerovandrei** [gophercloud/utils#42]
Currently this repo only supports `List` and `Get` methods for the Gnocchi archive policies.
We need to also add support for the `Create`, `Update` and `Delete` requests.

- [x] Gnocchi archive policy create (#43)
- [x] Gnocchi archive policy update (#44)
- [x] Gnocchi archive policy delete (#52)

Archive policies documentation reference:
https://gnocchi.xyz/rest.html#archive-policy

**Comment by jtopjian** [comment]
@ozerovandrei I have two things to apologize for:

1. I swear I left a comment last week about apologizing for the delay -- I was either imagining that or the comment never posted.
2. I just got a gnocchi environment up and running again, so I will be able to review these shortly. Sorry again for the delay.

**Comment by ozerovandrei** [comment]
@jtopjian there is no need to apologise.
Take your time, after all Gnocchi is not an OpenStack project (at least for now) 😄 

I hope to create additional issues and PRs regarding another Gnocchi objects - `resource types` and `archive policy rules`. So, please do not destroy your Gnocchi environment after this issue!

Also I have another two questions outside of scope of this issue:
- can you get the OpenLab acceptance tests runner working for this repository? (I forgot about acceptance tests by the way, will add them in PRs);
- can I contribute Gnocchi `archive policies`, `resource types` and `archive policy rules` to the terraform-provider-openstack in the future? We discussed Gnocchi status regarding OpenStack in the form of Gophercloud [issue#698](https://github.com/gophercloud/gophercloud/issues/698). But what about the provider? Sorry for off topic. (But if you allow it, acceptance runner in the OpenLab is necessary, I guess).

**Comment by jtopjian** [comment]
@ozerovandrei Thanks for implementing this :)

> can you get the OpenLab acceptance tests runner working for this repository?

I can see if OpenLab can integrate `gophercloud/utils`. It might take some work to get Gnocchi fully integrated, though, as I don't believe there's a devstack plugin for it.

> can I contribute Gnocchi archive policies, resource types and archive policy rules to the terraform-provider-openstack in the future?

I gave this some thought. After working with Gnocchi and revisiting the discussion at https://github.com/gophercloud/gophercloud/issues/698, I think it was a good call not to bundle Gnocchi into Gophercloud. I think Gnocchi is best thought of as a time series database with optional OpenStack support rather than an OpenStack time series database.

My main concern with integrating Gnocchi with the Terraform provider is that it would _require_ OpenStack to use Gnocchi rather than have Gnocchi be a standalone provider with optional OpenStack support.

I realize that 9/10 people would use Gnocchi+OpenStack, but given enough demand for Gnocchi-standalone, a separate provider would need created.

I'm going to close this issue but please feel free to continue this discussion if you have any questions or comments :)

**Comment by ozerovandrei** [comment]
@jtopjian thank you for a review.
Well, I'm of the same opinion about this, just wanted to hear your thoughts.
