### ISSUE TITLE
Gnocchi: resource types support

### ISSUE THREAD

**Issue by ozerovandrei** [gophercloud/utils#54]
It would be great if this repo supported API for Gnocchi resource types.

Documentation reference: [resource-types](https://gnocchi.xyz/rest.html#resource-types).

- [x] List resource types (#55)
- [x] Get a resource type (#59)
- [x] Create a resource type (#60)
- [x] Update a resource type (#61)
- [x] Delete a resource type (#62)
